#!/bin/bash

package_name="gcc"
package_version="14.2.0"
package_address="https://ftp.gnu.org/gnu/$package_name/$package_name-$package_version/$package_name-$package_version.tar.gz"

function do_configure
{
    cd "$package_source"

    "$package_source/contrib/download_prerequisites"

    cd "$package_build"

    sed --expression "/m64=/s/lib64/lib/" \
        --in-place "$package_source/gcc/config/i386/t-linux64"

    "$package_source/configure"              \
        --disable-libatomic                  \
        --disable-libgomp                    \
        --disable-libquadmath                \
        --disable-libssp                     \
        --disable-libstdcxx                  \
        --disable-libvtv                     \
        --disable-multilib                   \
        --disable-nls                        \
        --disable-shared                     \
        --disable-threads                    \
        --enable-default-pie                 \
        --enable-default-ssp                 \
        --enable-languages="c"               \
        --prefix="$toolchain_root/toolchain" \
        --target="$toolchain_target"         \
        --with-glibc-version="2.41"          \
        --with-newlib                        \
        --with-sysroot="$toolchain_root"     \
        --without-headers
}

function do_build
{
    make
}

function do_install
{
    make install

    cat "$package_source/gcc/limitx.h"  \
        "$package_source/gcc/glimits.h" \
        "$package_source/gcc/limity.h"  \
        > "$(dirname "$($toolchain_target-gcc -print-libgcc-file-name)")/include/limits.h"
}
