#!/bin/bash

package_name="glibc"
package_version="2.41"
package_address="https://ftp.gnu.org/gnu/$package_name/$package_name-$package_version.tar.gz"

function do_configure
{
    echo "rootsbindir=/usr/sbin" > "$package_source/configparms"

    "$package_source/configure"                      \
        --build="$(uname -m)-linux-gnu"              \
        --disable-nscd                               \
        --enable-kernel="5.4"                        \
        --host="$toolchain_target"                   \
        --prefix="/usr"                              \
        --with-headers="$toolchain_root/usr/include" \
        libc_cv_slibdir="/usr/lib"

    ln --symbolic "../lib/ld-linux-x86-64.so.2" "$toolchain_root/lib64"
}

function do_build
{
    make
}

function do_install
{
    make DESTDIR="$toolchain_root" install

    sed "/RTLDLIST=/s@/usr@@g" --in-place "$toolchain_root/usr/bin/ldd"
}
