#!/bin/sh

package_name="gcc"
package_version="12.2.0"
package_address="https://ftp.gnu.org/gnu/$package_name/$package_name-$package_version/$package_name-$package_version.tar.xz"
package_chroot="false"

package_configure()
{
    cd "$package_source"

    "$package_source/contrib/download_prerequisites"

    cd "$package_build"

    sed -e "/m64=/s/lib64/lib/" -i "$package_source/gcc/config/i386/t-linux64"

    "$package_source/configure"                                                \
        --target="$package_target"                                             \
        --prefix="$package_root/tools"                                         \
        --with-sysroot="$package_root"                                         \
        --with-glibc-version="2.37"                                            \
        --with-newlib                                                          \
        --without-headers                                                      \
        --disable-libatomic                                                    \
        --disable-libgomp                                                      \
        --disable-libquadmath                                                  \
        --disable-libssp                                                       \
        --disable-libstdcxx                                                    \
        --disable-libvtv                                                       \
        --disable-multilib                                                     \
        --disable-nls                                                          \
        --disable-shared                                                       \
        --disable-threads                                                      \
        --enable-default-pie                                                   \
        --enable-default-ssp                                                   \
        --enable-languages="c,c++"
}

package_build()
{
    make
}

package_install()
{
    make install

    compiler="$("$package_target-gcc" -print-libgcc-file-name)"

    cat "$package_source/gcc/limitx.h"                                         \
        "$package_source/gcc/glimits.h"                                        \
        "$package_source/gcc/limity.h"                                         \
        > "$(dirname "$compiler")/install-tools/include/limits.h"
}
