#!/bin/sh

package_name="m4"
package_version="1.4.19"
package_address="https://ftp.gnu.org/gnu/$package_name/$package_name-$package_version.tar.xz"
package_chroot="false"

package_configure()
{
    "$package_source/configure"                                                \
        --prefix="/usr"                                                        \
        --host="$package_target"                                               \
        --build="$("$package_source/build-aux/config.guess")"
}

package_build()
{
    make
}

package_install()
{
    make DESTDIR="$package_root" install
}
