#!/bin/sh

package_name="sed"
package_version="4.9"
package_address="https://ftp.gnu.org/gnu/$package_name/$package_name-$package_version.tar.xz"
package_chroot="false"

package_configure()
{
    "$package_source/configure"                                                \
        --prefix="/usr"                                                        \
        --host="$package_target"
}

package_build()
{
    make
}

package_install()
{
    make DESTDIR="$package_root" install
}
