#!/bin/sh

package_name="xz"
package_version="5.4.1"
package_address="https://tukaani.org/$package_name/$package_name-$package_version.tar.xz"
package_chroot="false"

package_configure()
{
    "$package_source/configure"                                                \
        --prefix="/usr"                                                        \
        --host="$package_target"                                               \
        --build="$("$package_source/build-aux/config.guess")"                  \
        --docdir="/usr/share/doc/$package_name-$package_version"               \
        --disable-static
}

package_build()
{
    make
}

package_install()
{
    make DESTDIR="$package_root" install

    rm "$package_root/usr/lib/liblzma.la"
}
