#!/bin/sh

package_name="bison"
package_version="3.8.2"
package_address="https://ftp.gnu.org/gnu/$package_name/$package_name-$package_version.tar.xz"
package_chroot="true"

package_configure()
{
    "$package_source/configure"                                                \
        --prefix="/usr"                                                        \
        --docdir="/usr/share/doc/$package_name-$package_version"
}

package_build()
{
    make
}

package_install()
{
    make install
}
