#!/bin/sh

package_name="perl"
package_version="5.36.0"
package_address="https://www.cpan.org/src/5.0/$package_name-$package_version.tar.gz"
package_chroot="true"

package_configure()
{
    cd "$package_source"

    sh Configure                                                               \
        -des                                                                   \
        -Dprefix="/usr"                                                        \
        -Dvendorprefix="/usr"                                                  \
        -Dprivlib="/usr/lib/perl5/5.36/core_perl"                              \
        -Darchlib="/usr/lib/perl5/5.36/core_perl"                              \
        -Dsitelib="/usr/lib/perl5/5.36/site_perl"                              \
        -Dsitearch="/usr/lib/perl5/5.36/site_perl"                             \
        -Dvendorlib="/usr/lib/perl5/5.36/vendor_perl"                          \
        -Dvendorarch="/usr/lib/perl5/5.36/vendor_perl"
}

package_build()
{
    cd "$package_source"

    make
}

package_install()
{
    cd "$package_source"

    make install
}
