#!/bin/sh

package_name="python"
package_version="3.11.2"
package_address="https://www.python.org/ftp/$package_name/$package_version/Python-$package_version.tar.xz"
package_chroot="true"

package_configure()
{
    "$package_source/configure"                                                \
        --prefix="/usr"                                                        \
        --enable-shared                                                        \
        --without-ensurepip
}

package_build()
{
    make
}

package_install()
{
    make install
}
