#!/bin/sh

toolchain_package_directory()
{
    toolchain_package_directory="$toolchain_mount/packages"

    if [ ! -d "$toolchain_package_directory" ]
    then
        mkdir "$toolchain_package_directory"
    fi
}

toolchain_package_address()
{
    toolchain_package_address="$(toolchain_recipe_property '$package_address')"

    if [ -z "$toolchain_package_address" ]
    then
        toolchain_console_error "Package address: $toolchain_package_address"
    fi

    toolchain_console_success "Package address: $toolchain_package_address"
}

toolchain_package_chroot()
{
    toolchain_package_chroot="$(toolchain_recipe_property '$package_chroot')"

    if [ -z "$toolchain_package_chroot" ]
    then
        toolchain_console_error "Package chroot: $toolchain_package_chroot"
    fi

    toolchain_console_success "Package chroot: $toolchain_package_chroot"
}
